### ISSUE TITLE
Typo and CSS issue causes overflow

### ISSUE THREAD

**Issue by mertyildiran** [descope/react-sdk#290]
![Screenshot from 2023-05-19 03-04-31](https://github.com/descope/react-sdk/assets/2502080/82b0f1dc-a990-44d1-bf80-02770aad7997)

There is this **infomration** typo in the title and a CSS issue causes overflow hence the scrollbar.

**Version**: `1.0.3`

**Comment by asafshen** [comment]
Thanks for reporting! 

We have manage to locate and reproduce and we will fix those issues soon

**Comment by asafshen** [comment]
@mertyildiran just a quick FYI reg the infomration typo

the screen template will be fixed soon, but in the meantime - you can edit the screen in [Descope console](https://app.descope.com/flows)  flows page

The screen is under "Sign Up Or In" flow -> "User Information - Unverified - Phone Only" Screen, and then you can mark the title with the typo

![image](https://github.com/descope/react-sdk/assets/10514677/f9ddd985-12fe-480b-beb3-d5e4b9f75812)
![image](https://github.com/descope/react-sdk/assets/10514677/5c250bba-3112-441f-8d79-77d4427e294d)
![image](https://github.com/descope/react-sdk/assets/10514677/07d04795-560d-4c67-89d7-f518ddcdcd6a)

**Comment by asafshen** [comment]
@mertyildiran a quick update reg the CSS issue, we also found and fixed the issue locally, but as a temporary work-around, you can go to the page above, and replace the current "phone number" component with a new one
simply drag and drop the component, and then click on the previous component and delete it (delete button is in the right panel)

![image](https://github.com/descope/react-sdk/assets/10514677/532e34c4-dfc6-4c2c-9268-f9a56f40b920)

**Comment by asafshen** [comment]
this issue has been resolved, thanks for reporting!
