### ISSUE TITLE
What does `PublicKeyCredential is not defined` error mean?

### ISSUE THREAD

**Issue by mertyildiran** [descope/react-sdk#291]
![Screenshot from 2023-05-19 03-20-45](https://github.com/descope/react-sdk/assets/2502080/8b116b20-4a50-4baa-925c-0ce67e1ad9b7)

Clicking the continue buttons print the error below into the console:

```
Uncaught (in promise) ReferenceError: PublicKeyCredential is not defined
    at index-b7476a59.js:2:4291
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at Cr (index-b7476a59.js:2:4306)
```

**Version**: `1.0.3`

**Comment by dorsha** [comment]
@mertyildiran we need more details here.
Exact steps to reproduce.
Project id.

**Comment by dorsha** [comment]
Thanks! 
We are looking into this.

**Comment by asafshen** [comment]
hey @mertyildiran 

Thanks for the feedback

few follow-up questions: I see you are using chrome 113, may I ask which OS + version are you using?

The reason that I'm asking is because the `PublicKeyCredential` is a browser API that is used in a dependency of the react sdk  (which is [another Descope package](https://github.com/descope/descope-js/tree/main/packages/web-js-sdk)) for biometrics authentication support

I see in most of the places, it consider a case where the browser is not support it, but there can be a flaw in the way it is done, or maybe a place that it misses to check that it is support it


```

**Comment by mertyildiran** [comment]
> hey @mertyildiran
> 
> Thanks for the feedback
> 
> few follow-up questions: I see you are using chrome 113, may I ask which OS + version are you using?
> 
> The reason that I'm asking is because the `PublicKeyCredential` is a browser API that is used in a dependency of the react sdk (which is [another Descope package](https://github.com/descope/descope-js/tree/main/packages/web-js-sdk)) for biometrics authentication support
> 
> I see in most of the places, it consider a case where the browser is not support it, but there can be a flaw in the way it is done, or maybe a place that it misses to check that it is support it

### Browser and OS
Chrome: `Version 113.0.5672.92 (Official Build) (64-bit)`
Linux distro: `Ubuntu 20.04 LTS`
Kernel version: `6.0.12-76060012-generic`

### NPM

`react` version: `17.0.2`
`react-scripts` version: `5.0.1`
`@descope/react-sdk`: version: `1.0.3`
`webpack` version: `5.83.1`

`package.json`:

```json
"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version"
  ]
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "esnext",
    "lib": [
      "dom",
      "esnext",
      "dom.iterable"
    ],
    "moduleResolution": "node",
    "jsx": "react-jsx",
    "sourceMap": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "downlevelIteration": true,
    "noFallthroughCasesInSwitch": true,
    "target": "es5",
    "esModuleInterop": true
  },
  "include": [
    "src",
    "src/types"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "example"
  ]
}
```

**Comment by mertyildiran** [comment]
By the way, it happens specifically when I build the Docker image:

```Dockerfile
FROM node:16-alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build
```

Maybe related to being `node:16-alpine` I don't know. The local build does not reproduce the issue.

**Comment by asafshen** [comment]
> By the way, it happens specifically when I build the Docker image:
> 
> 
> 
> ```Dockerfile
> 
> FROM node:16-alpine as builder
> 
> WORKDIR /app
> 
> COPY package.json package-lock.json ./
> 
> RUN npm ci --omit=dev
> 
> COPY . .
> 
> RUN npm run build
> 
> ```
> 
> 
> 
> Maybe related to being `node:16-alpine` I don't know. The local build does not reproduce the issue.

Got it, thanks for the tip

**Comment by asafshen** [comment]
@mertyildiran the fix is available in the latest `next` version `@descope/react-sdk@next` version, and will be generally available in the next release

to use latest next version you can install it directly:
```
npm i --save @descope/react-sdk@0.0.0-next-dd59e8aa-20230521
```

**Comment by mertyildiran** [comment]
> @mertyildiran the fix is available in the latest `next` version `@descope/react-sdk@next` version, and will be generally available in the next release
> 
> to use latest next version you can install it directly:
> 
> ```
> npm i --save @descope/react-sdk@0.0.0-next-dd59e8aa-20230521
> ```

Thanks for the update @asafshen!

I have upgraded to `@descope/react-sdk@0.0.0-next-dd59e8aa-20230521` but it seems like there is a new error now:

```
Uncaught TypeError: t.get is not a function
    at o (tslib.es6.js:209:23)
    at new n (index-84419228.js:1:5757)
    at n.<anonymous> (createSuper.js:11:24)
    at new n (index-84419228.js:1:12631)
    at rs (react-dom.production.min.js:206:287)
    at Cl (react-dom.production.min.js:251:81)
    at xl (react-dom.production.min.js:250:408)
    at Tl (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
```

and the login form does not appear.

**Comment by asafshen** [comment]
@mertyildiran thanks fro the quick feedback

I could not reproduce (yet) this error, are you sure that this error comes from the Descope sdk code?

few questions:
1. Do you have a way to run the application with a sourcemap, so we can see the exception call-stack with proper names/files?
2. Does the error happen when the code is running both locally and served from a docker container? 
3. I have created a simple application that runs a simple react application inside a docker container (fyi it is running against mine Descope project). can you see if that reproduce there when you run it? can you change the code/create a simple open source example where this reproduces? 

I'm here for any questions

**Comment by mertyildiran** [comment]
@asafshen I have created a new issue here: https://github.com/descope/react-sdk/issues/301
