### ISSUE TITLE
Need your help to integrate descope (version: 1.0.14)

### ISSUE THREAD

**Issue by ziaul-haque** [descope/react-sdk#429]
./node_modules/@descope/react-sdk/dist/index.esm.js 34:22
Module parse failed: Unexpected token (34:22)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   projectId: "temp pid"
| });
> const w = () => m ? k?.getSessionToken() : (console.warn("Get session token is not supported in SSR"), ""),
|   y = () => m ? k?.getRefreshToken() : (console.warn("Get refresh token is not supported in SSR"), ""),
|   b = p((e = w(), r) => k?.getJwtPermissions(e, r)),

Node: 14.18.2
React: 17.0.1
react-scripts: "4.0.1"

Kindly help.

**Comment by asafshen** [comment]
jey @ziaul-haque 

thanks for the detailed information 

any chance that you have a small repository that reproduces this issue?
