### ISSUE TITLE
DescopeInterceptor for reactSDK

### ISSUE THREAD

**Issue by laxmipsarva** [descope/react-sdk#459]
I am trying to catch 401 while fetching refresh token in react sdk I found DescopeInterceptor in angular sdk is there a way to catch 401/403 while refresh token

**Comment by asafshen** [comment]
Hey @laxmipsarva 

Have you looked on the onSessionChaned hook?

It is also called when the token is reset after 401 (when session expires)

Maybe something like the following 
```
const sdk = useDescope()

useEffect(() = > {
  sdk.onSessionChange(session => {
    if (!session) { ... }
  })
}, [sdk])
```

**Comment by asafshen** [comment]
Hey @laxmipsarva 

Have you looked on the onSessionChaned hook?

It is also called when the token is reset after 401 (when session expires)

Maybe something like the following 
```
const sdk = useDescope()

useEffect(() = > {
  sdk.onSessionChange(session => {
    if (!session) { ... }
  })
}, [sdk])
```

**Comment by laxmipsarva** [comment]
Thank you
