### ISSUE TITLE
 "Fingerprint is a client side only capability" Error when Importing AuthProvider

### ISSUE THREAD

**Issue by nenostra** [descope/react-sdk#531]
When importing `AuthProvider` from `@descope/react-sdk` in a Next.js project, the following error occurs:
"Fingerprint is a client side only capability and will not work when running in the server"

#### Steps to Reproduce
1. Bootstrap a new Next.js project:
   npx create-next-app@latest my-next-app
   cd my-next-app
2. Install `@descope/react-sdk`:
   npm install @descope/react-sdk
3. Modify the `_app.tsx` file to import `AuthProvider`:
```
import { AuthProvider } from "@descope/react-sdk";

   function MyApp({ Component, pageProps }) {
     return (
       <AuthProvider>
         <Component {...pageProps} />
       </AuthProvider>
     );
   }

   export default MyApp;
```   
4. Build the app:
   `npm run build`
5. Observe the error in the console.

#### Expected Behavior
The `AuthProvider` should work without errors when imported and used with SSR.

#### Environment
- Next.js version: 14.2.4 with pages folder
- `@descope/react-sdk` version: 2.0.40

Any help appreciated, thanks!

**Comment by asafshen** [comment]
Hey @nenostra , thanks for reporting this

This is indeed a log that should not be presented in SSR, so for now, I advice to ignore this log line if thats an option

We'll make sure to fix this as soon as possible
